name: max_count
description: Flutter Realtime Game

publish_to: 'none' 

version: 1.2.2+7

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_native_splash: ^2.2.14
  auto_size_text: ^3.0.0
  firebase_database: ^10.0.5
  firebase_core: ^2.2.0
  just_audio: ^0.9.18
  internet_connection_checker: ^1.0.0+1
  provider: ^6.0.4
  rounded_loading_button: ^2.0.5
  shared_preferences: ^2.0.12
  audio_session: ^0.1.6+1
  audio_service: ^0.18.1
  just_audio_platform_interface: ^4.0.0
  google_mobile_ads: ^2.2.0
  nice_intro: ^0.2.1
  flutter_styled_toast: ^2.0.0
  firebase_app_check: ^0.1.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#5ED466"
  adaptive_icon_foreground: "assets/launcher_icon/foreground.png"

flutter:

  uses-material-design: true

  assets:
     - assets/
     - assets/sounds/


  fonts:
    - family: PixelTitle
      fonts:
        - asset: fonts/pixelTitle.ttf
          style: italic

